version : '3.9'
services:
      mongo_db : 
          container_name : db_container
          image : mongo:latest
          restart : always
          volumes : 
                - mongo_db:'data/db'
   
app :
  build : .
  ports : 
      - 3000:3000
  enviroment :
      ports : 3000
      MONGODB_URI : mongo_db:27017
      DB_NAME : node
      NAME : story_book
depends_on :
      - mongo_db

volumes : 
      mongo_db : {}